# Generated by Django 5.2.4 on 2025-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(max_length=20, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.FloatField(verbose_name='별점'),
        ),
    ]
