# Generated by Django 5.2.4 on 2025-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_moviereview_genre_alter_moviereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='running_time',
            field=models.CharField(max_length=50, verbose_name='러닝타임(분)'),
        ),
    ]
