# Generated by Django 5.2.4 on 2025-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_moviereview_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.CharField(max_length=50, verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='release_year',
            field=models.CharField(max_length=50, verbose_name='개봉년도'),
        ),
    ]
